language: node_js

node_js:
  - "node"

script:
  - npm run test

deploy:
  provider: s3
  access_key_id: $AWS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  region: $AWS_REGION
  local_dir: data
  skip_cleanup: true
  on:
    branch: master
